name: Presubmit checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - run: |  # Needed for git diff to work.
          git fetch origin master --depth 1
          git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Pull CI image
        run: docker pull gcr.io/clusterfuzz-images/ci

      - name: Run tests
        run: ./local/tests/ci_tests.bash

